services:
  mysql:
    image: mysql:9.2.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 53cret
      MYSQL_DATABASE: distrimo
      MYSQL_USER: yu71
      MYSQL_PASSWORD: 53cret
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
