server:
  port: 8080

spring:
  profiles:
    active: "dev"
  application:
    name: "spring-boot-distributed-monitoring"
  datasource:
    url: jdbc:mysql://localhost:3307/distrimo?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Jakarta
    username: yu71
    password: 53cret
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    show-sql: true # Enables SQL queries in logs
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true # Formats SQL for better readability
        use_sql_comments: true # Adds comments to the SQL output

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    io.micrometer.tracing: DEBUG
    zipkin2: DEBUG

management:
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: distrimo-backend-service
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans
